spring:

  datasource:
    url: jdbc:postgresql://localhost:5433/BatWoman_db
    username: AfiyaKhalid
    password: Peekaboo
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
razorpay:
  key-id: rzp_test_TE5cqRrow9WPtc
  key-secret: FlFjlGWU7Gt3MujEcY02Bk4Y