"use client";

import {

    ResponsiveContainer,

    AreaChart,

    Area,

    CartesianGrid,

    Tooltip,

    XAxis,

    YAxis,

} from "recharts";

import { MonthlyRevenue } from "@/services/adminAnalytics.service";

interface RevenueChartProps {

    data: MonthlyRevenue[];

}

export default function RevenueChart({

    data,

}: RevenueChartProps) {

    return (

        <div className="rounded-3xl border border-neutral-200 bg-white p-8 shadow-sm">

            <div className="mb-8">

                <h2 className="text-2xl font-semibold">

                    Revenue Trend

                </h2>

                <p className="mt-2 text-neutral-500">

                    Monthly revenue generated by completed orders.

                </p>

            </div>

            <div className="h-[420px]">

                <ResponsiveContainer width="100%" height="100%">

                    <AreaChart
                        data={data}
                        margin={{
                            top: 10,
                            right: 20,
                            left: 0,
                            bottom: 0,
                        }}
                    >

                        <defs>

                            <linearGradient
                                id="revenueGradient"
                                x1="0"
                                y1="0"
                                x2="0"
                                y2="1"
                            >

                                <stop
                                    offset="5%"
                                    stopColor="#111827"
                                    stopOpacity={0.35}
                                />

                                <stop
                                    offset="95%"
                                    stopColor="#111827"
                                    stopOpacity={0}
                                />

                            </linearGradient>

                        </defs>

                        <CartesianGrid
                            strokeDasharray="4 4"
                            vertical={false}
                        />

                        <XAxis
                            dataKey="month"
                            tickLine={false}
                            axisLine={false}
                        />

                        <YAxis
                            tickLine={false}
                            axisLine={false}
                        />

                        <Tooltip />

                        <Area
                            type="monotone"
                            dataKey="revenue"
                            stroke="#111827"
                            strokeWidth={4}
                            fill="url(#revenueGradient)"
                        />

                    </AreaChart>

                </ResponsiveContainer>

            </div>

        </div>

    );

}